### ISSUE TITLE
val_3 driver: rough and jerky trajectories

### ISSUE THREAD

**Issue by nilsmelchert** [ros-industrial/staubli_experimental#25] opened 2018-04-24 10:45 UTC
After working a while with `ros kinetic` and the `val_3 driver` in the `staubli_experimental` package, I figured that the executed trajectories of the real robot are not running very smoothly. Especially in the end of an executed path the movement is quite chopped.
Did also experience the same thing? Could there be a problem with the driver? Or is there a problem with the `ompl` library?

**Comment by gavanderhoorn** [comment] 2018-04-24 10:49
The driver could always play a role (it hasn't been tested *very* extensively, partly why it is in an experimental repository), but if you're using Kinetic and MoveIt, you may be running into ros-planning/moveit#416 or related issues.

See ros-industrial/kuka_experimental#126 for a possibly related issue, and some links to relevant other issues.

I'm not saying this is the cause of what you're seeing, but it would be good to check this.

One way to see whether Kinetic OMPL is doing strange things is to generate a trajectory in some other way, time-parameterise it yourself and then send it to the driver directly.

> Especially in the end of an executed path the movement is quite clipped.

I'm not sure I completely understand what you're describing here. What do you mean with 'clipped'?

**Comment by nilsmelchert** [comment] 2018-04-25 07:14
> I'm not sure I completely understand what you're describing here. What do you mean with 'clipped'?

By clipped I meant very jerky. 

Yes [ros-planning/moveit#416](https://github.com/ros-planning/moveit/issues/416) seems to describe exactly  the behaviour of my trajectories. I would guess that the content of the second comment in [this answer](https://github.com/ros-planning/moveit/issues/416#issuecomment-273718781) could be a reason for the jerky trajectory execution.

**Comment by gavanderhoorn** [comment] 2018-04-25 07:23
Thing is, the time parameterisation code hadn't changed much (at all actually) between Indigo and Kinetic, until ros-planning/moveit#441 got merged. That seemed to point to *something else* that was interfering here. As you can read further down in ros-planning/moveit#416, it would seem that changes to OMPL itself have introduced this. This was reported in [bitbucket/ompl/ompl#309](https://bitbucket.org/ompl/ompl/issues/309/performance-regression-going-from-ompl).

The comment you link to (it's not an answer) suggests that it's mostly the time parameterisation. As I hope is now clear, that could be related, but is most likely not the cause. A strong hint for that is that the reporter of [bitbucket/ompl/ompl#309](https://bitbucket.org/ompl/ompl/issues/309/performance-regression-going-from-ompl) mentions in the second comment on his own issue that:

> I tested the following diff and the jerky trajectories are gone now.

Where "the following diff" undoes some changes to the trajectory generation parts of OMPL itself.

I believe it would make sense to see whether generating a path through some other means and then time parameterising it would immediately make clear whether or not OMPL is affecting this. Alternatively, have an Indigo version of MoveIt generate a trajectory and execute that. If that doesn't exhibit this behaviour, I believe it would point to OMPL again.

It would also be good to check whether configuring MoveIt to use TOTG improves things (ros-planning/moveit#809).

But that is all mentioned in ros-industrial/kuka_experimental#126 already.

**Comment by gavanderhoorn** [comment] 2018-04-28 17:54
According to the latest comments on ros-planning/moveit#416, the issue with OMPL is now fixed and is going to be backported to Kinetic.

**Comment by nilsmelchert** [comment] 2018-04-28 18:12
Thank you very much! I will close this Issue now.

**Comment by nilsmelchert** [comment] 2018-04-28 19:11
When will I be able to update the fix for this Problem? Will it be updatable in the apt-tree or would I have to apply the changes myself with some kind of patch which will be published?

What are the next steps?

**Comment by gavanderhoorn** [comment] 2018-04-28 19:16
The fix first needs to be verified. Then it needs to be backported to Kinetic. MoveIt/OMPL will need a new release, and that will need to be synced to the public repositories.

It could take some time. Building OMPL from source on Kinetic -- and thus MoveIt as well -- will make it available earlier to you.

Note also btw that it's not certain that this is the cause of what you describe. It's a good candidate, but there are no guarantees.

**Comment by gavanderhoorn** [comment] 2018-04-28 19:16
I recommend you keep a close eye on ros-planning/moveit#416.

**Comment by gavanderhoorn** [comment] 2018-06-19 11:12
Have you seen any improvement @nilsmelchert with the release of the new MoveIt+OMPL?

**Comment by nilsmelchert** [comment] 2018-06-22 07:24
To be honest, I have not worked with the robots for about a month. Do I have to compile MoveIt from source or is it already available via apt-get?

I will test it on monday and then present the results.

**Comment by gavanderhoorn** [comment] 2018-06-22 07:29
MoveIt & OMPL on Kinetic should have all the updates. No need for a source build.

**Comment by nilsmelchert** [comment] 2018-06-22 07:30
Ok. I will test if there is any improvement and then post the results.

**Comment by gavanderhoorn** [comment] 2018-06-22 07:35
One thing to check btw is that the `reach` and `leave` setting for each trajectory point in the driver is set to really low values, so the controller cannot do much blending.

That could also be the cause of some jittering.

See [this diff](https://github.com/ros-industrial/staubli_experimental/compare/indigo-devel...MPJansen:684da890) for another user that experimented a bit with that.

Ideally blending should not be used, but if all else fails, it might be something to look into.

**Comment by gavanderhoorn** [comment] 2018-11-02 19:26
@nilsmelchert: has this improved at all for you?

**Comment by nilsmelchert** [comment] 2018-11-07 10:27
@gavanderhoorn I just tested it. And yes it works perfectly fine. Thanks!
I will close the Issue now.

**Closed as completed** 2019-05-09 05:57 UTC
